name: Make new release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: Create and publish release
    runs-on: ubuntu-latest
    environment: Make kbo release

    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build_artifacts.yml
          workflow_conclusion: success

      - name: Organise files
        shell: bash
        run: |
          mv kbo-candidate-x86_64-unknown-linux-musl/kbo-candidate-x86_64-unknown-linux-musl.tar.gz ./
          mv kbo-candidate-x86_64-apple-darwin/kbo-candidate-x86_64-apple-darwin.tar.gz ./
          mv kbo-candidate-aarch64-apple-darwin/kbo-candidate-aarch64-apple-darwin.tar.gz ./

      - name: Rename mac artifacts
        shell: bash
        run: |
          tar -zxvf kbo-candidate-x86_64-apple-darwin.tar.gz && mv kbo-candidate-x86_64-apple-darwin kbo-${{ github.ref_name }}-x86_64-apple-darwin && tar -zcvf kbo-candidate-x86_64-apple-darwin.tar.gz kbo-${{ github.ref_name }}-x86_64-apple-darwin
          tar -zxvf kbo-candidate-aarch64-apple-darwin.tar.gz && mv kbo-candidate-aarch64-apple-darwin kbo-${{ github.ref_name }}-aarch64-apple-darwin && tar -zcvf kbo-candidate-aarch64-apple-darwin.tar.gz kbo-${{ github.ref_name }}-aarch64-apple-darwin

      - name: Designate version
        shell: bash
        run: |
          mv kbo-candidate-x86_64-unknown-linux-musl.tar.gz kbo-${{ github.ref_name }}-x86_64-linux-musl.tar.gz
          mv kbo-candidate-x86_64-apple-darwin.tar.gz kbo-${{ github.ref_name }}-x86_64-apple-darwin.tar.gz
          mv kbo-candidate-aarch64-apple-darwin.tar.gz kbo-${{ github.ref_name }}-aarch64-apple-darwin.tar.gz

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d %B %Y')"

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.MAKE_RELEASE_TOKEN }}
          name: kbo-${{ github.ref_name }} (${{ steps.date.outputs.date }})
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            kbo-${{ github.ref_name }}-x86_64-linux-musl.tar.gz
            kbo-${{ github.ref_name }}-x86_64-apple-darwin.tar.gz
            kbo-${{ github.ref_name }}-aarch64-apple-darwin.tar.gz